services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=shuttler'
      - 'MONGO_INITDB_ROOT_PASSWORD=testPass'
      - 'MONGO_INITDB_ROOT_USERNAME=payhez'
    ports:
      - '27017:27017'
    volumes:
      - shuttlerdata:/data/db
volumes:
  shuttlerdata:
