spring:
  application:
    name: shuttler
  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27018,localhost:27019/shuttler?replicaSet=rs0
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: shuttler
            client-secret: kcnwlBvVSPlT2Jbzce4LZuiAmLmQ0L76
            scope: openid, profile, email
            authorization-grant-type: client_credentials
            redirect-uri: http://localhost:8080
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/shuttler
keycloak:
  admin:
    serverUrl: http://localhost:8081
    realm: shuttler
    adminUser: admin
    adminPassword: adminPass
    clientId: admin-cli
    adminRealm: master