server:
  port: 8081

spring:
  application:
    name: shuttler-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user/**
      httpclient:
        response-timeout: 10s
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8001/auth/realms/Shuttler/protocol/openid-connect/token
            authorization-uri: http://localhost:8001/auth/realms/Shuttler/protocol/openid-connect/auth
            user-info-uri: http://localhost:8001/auth/realms/Shuttler/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          shuttler-scope:
            provider: keycloak
            client-id: shuttler-gateway
            client-secret: sLSx5EXaykmNppm7CVI8mbtAEwMc4CP4
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"